-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjHjSYofr2B21kAP4
qzs1Te7qdhrQHeqNUkXexnb64BygCgYIKoZIzj0DAQehRANCAAScnJhpjHWNI9Fi
cRAd+vr2tYt3jw1Ej/s3zGEQ/srXuRpA4/Wj3ncuHTjpa1jaji/kcQ3p3iSBxBjq
OuB/8Hqc
-----END PRIVATE KEY-----